### ISSUE TITLE
[Bug] Release of ng19 broke npm dependencies between @ng-doc and @angular

### ISSUE THREAD

**Issue by MatthewMarichiba** [ng-doc/ng-doc#248] opened 2024-11-25 20:54 UTC
### Is this a regression?

Yes

### Description

Something about the Angular 19 release broke dependencies in @ng-doc version 18.x. (I also tested with the last v17 @ng-doc release, and the same defect occurs.) The minimal package.json provided below is enough to cause the defect. `@ng-doc/app` and `@ng-doc/ui-kit` appear to be the offending packages; removing them from package.json clears the issue.

The defect seems to be dependent on the presence of ng19 in the world. We were fine until last week. Then ng19 released to the public npm repo. Then our CI builds started breaking.

Thank you!

### Please provide the exception or error you saw

```true
[~/test-ng-doc][]
$ rm -rf node_modules/

[~/test-ng-doc][]
$ cat package.json 
{
    "name": "break-ng-doc18",
    "description": "This file tests breaking ng-doc",
    "dependencies": {
        "@angular/cdk": "^18.0",
        "@angular/common": "^18.0",
        "@ng-doc/app": "^18.0",
        "@ng-doc/builder": "^18.0",
        "@ng-doc/core": "^18.0",
        "@ng-doc/ui-kit": "^18.0"
    }
}

[~/test-ng-doc][]
$ npm install
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: break-ng-doc18@undefined
npm error Found: @angular/common@18.2.12
npm error node_modules/@angular/common
npm error   @angular/common@"^18.0" from the root project
npm error   peer @angular/common@">=18.1.0" from @ng-doc/app@18.3.0
npm error   node_modules/@ng-doc/app
npm error     @ng-doc/app@"^18.0" from the root project
npm error   1 more (@angular/cdk)
npm error
npm error Could not resolve dependency:
npm error peer @angular/common@"19.0.0" from @angular/router@19.0.0
npm error node_modules/@angular/router
npm error   peer @angular/router@">=18.1.0" from @ng-doc/app@18.3.0
npm error   node_modules/@ng-doc/app
npm error     @ng-doc/app@"^18.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /home/matthew.marichiba/.npm/_logs/2024-11-25T20_48_48_325Z-eresolve-report.txt
npm error A complete log of this run can be found in: /home/matthew.marichiba/.npm/_logs/2024-11-25T20_48_48_325Z-debug-0.log

[~/test-ng-doc][]
$  
```
```


### OS

Unix (Linux, macOS, etc.)

### Browser

None

### Node version

20.12.2, 22.6.0

### Anything else?

_No response_

**Comment by bingbongboop** [comment] 2024-11-26 17:18
@skoropadas I'm seeing this same issue. This is NOT a duplicate of [#247](https://github.com/ng-doc/ng-doc/issues/247). 

I'm using an Angular 18 application, trying to just do an `npm i` with `"@ng-doc/app": "^18.0"` as a dependency.

The issue is with the ng-doc app package.json [file](https://github.com/ng-doc/ng-doc/blob/main/libs/app/package.json).

The peer dependencies are listing versions "greater than" 18, so since Angular 19 came out Angular CDK 19 will be installed, even though I'm running an Angular 18 project.
`"@angular/cdk": ">=18.1.0"`

**Comment by skoropadas** [comment] 2024-11-26 17:49
Hm ok, I see, I'll check it

**Comment by skoropadas** [comment] 2024-11-26 18:01
I'm releasing a fix with 18.3.1 version, could you check and confirm that it works for you?

**Comment by bingbongboop** [comment] 2024-11-26 18:02
Will do!

**Comment by bingbongboop** [comment] 2024-11-26 21:06
Now it seems there's another dependency issue with `@tinkoff/ng-polymorpheus@4.3.0`.

```
npm error Found: @angular/common@18.2.13
npm error node_modules/@angular/common
npm error   dev @angular/common@"^18.2" from the root project
npm error   peer @angular/common@">= 18.1.0 < 19.0.0" from @ng-doc/ui-kit@18.3.1
npm error   node_modules/@ng-doc/ui-kit
npm error     dev @ng-doc/ui-kit@"18.3.1" from the root project
npm error   1 more (@angular/cdk)
npm error
npm error Could not resolve dependency:
npm error peer @angular/common@"19.0.1" from @angular/platform-browser@19.0.1
npm error node_modules/@angular/platform-browser
npm error   peer @angular/platform-browser@">=12.0.0" from @tinkoff/ng-polymorpheus@4.3.0
npm error   node_modules/@tinkoff/ng-polymorpheus
npm error     peer @tinkoff/ng-polymorpheus@"4.3.0" from @ng-doc/ui-kit@18.3.1
npm error     node_modules/@ng-doc/ui-kit
npm error       dev @ng-doc/ui-kit@"18.3.1" from the root project
```

**Comment by skoropadas** [comment] 2024-12-08 15:16
@bingbongboop do you have a repo that I could take a look? can't reproduce this issue locally on a new project

**Comment by skoropadas** [comment] 2024-12-23 09:31
I was unable to reproduce this issue on several of my projects that I updated to Angular 19. My steps were as follows:

- Update dependencies in `package.json` to Angular 19 and NgDoc 19
- Delete `node_modules` and `package-lock.json`
- Run `npm i`

This worked on all projects without causing dependency issues. I will close the ticket, but if you are still experiencing this problem, please reopen it and provide a repository where I can reproduce the issue.

**Closed by skoropadas** 2024-12-23 09:31 UTC
Labels: Type: Bug
