### ISSUE TITLE
[Bug] JIT compilation failed for injectable [class PlatformNavigation]

### ISSUE THREAD

**Issue by jimmy1993k** [ng-doc/ng-doc#198] opened 2024-08-19 14:38 UTC
### Is this a regression?

No

### Description

Whenever I add a FormControl as a data field to a ng-doc.page.ts file, I will get an error saying something about the JIT compiler. 
I have tried the following suggestions from the error message:

- put the `import '@angular/compiler';` statement on the first line of my main.ts 
- bootstrap the application using `platformBrowserDynamic` from `@angular/platform-browser-dynamic` instead of the `bootstrapApplication` from `@angular/platform-browser`

The same error persists.

My `ng-doc.page.ts` file looks like this:

```
import { NgDocPage } from '@ng-doc/core';
import CommonComponentsCategory from '../ng-doc.category';
import { InputFieldComponentComponent } from './input-field-component/input-field-component.component';
import { CommonComponentsModule } from '@app/shared/common';
import { InputFieldComponent } from '@app/shared/common/components/molecule/input-field/input-field.component';
import { FormControl, ReactiveFormsModule } from '@angular/forms';

const InputFieldPage: NgDocPage = {
  title: `Input Field`,
  mdFile: './index.md',
  category: CommonComponentsCategory,
  demos: { InputFieldComponentComponent },
  imports: [CommonComponentsModule, ReactiveFormsModule],
  playgrounds: {
    InputFieldPlayground: {
      target: InputFieldComponent,
      template: `<ng-doc-selector [formControl]="data.formControl"></ng-doc-selector>`,
      inputs: {
        type: 'text',
        label: 'Playground',
      },
      data: {
        formControl: new FormControl(''),
      },
    },
  },
};

export default InputFieldPage;
```

### Please provide the exception or error you saw

```true
\ NgDoc: Loading...JIT compilation failed for injectable [class PlatformNavigation]

× NgDoc: 1 entities with problems:
×   projects\ng-doc\src\common-components\input-field\ng-doc.page.ts:
×     Error: The injectable 'PlatformNavigation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.

The injectable is part of a library that has been partially compiled.
However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.

Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
×     Error: The injectable 'PlatformNavigation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.

The injectable is part of a library that has been partially compiled.
However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.

Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
```

### OS

Windows

### Browser

None

### Node version

v20.16.0

**Comment by skoropadas** [comment] 2024-08-19 16:55
It seems that this bug was fixed in the NgDoc18, at least I can't reproduce it there, so I would ask you to wait for the NgDoc 18 release

**Comment by skoropadas** [comment] 2024-08-23 15:39
Released in NgDoc 18, feel free to reopen the ticket

**Closed by skoropadas** 2024-08-23 15:39 UTC
Labels: Type: Bug
